# Generated by Django 3.2.4 on 2022-04-12 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(default='user', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_task_time', models.DateTimeField(auto_created=True)),
                ('assignee_name', models.TextField()),
                ('task_name', models.TextField()),
                ('description', models.TextField()),
                ('total_work_log', models.IntegerField()),
                ('updated_worklog', models.IntegerField()),
                ('created_task_time', models.DateTimeField(auto_now_add=True)),
                ('Priority', models.TextField(choices=[('HIGH', 'HIGH'), ('LOW', 'LOW'), ('MEDIUM', 'MEDIUM')])),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.user')),
            ],
        ),
        migrations.CreateModel(
            name='InProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_task_time', models.DateTimeField(auto_created=True)),
                ('assignee_name', models.TextField()),
                ('task_name', models.TextField()),
                ('description', models.TextField()),
                ('total_work_log', models.IntegerField()),
                ('updated_worklog', models.IntegerField()),
                ('created_task_time', models.DateTimeField(auto_now_add=True)),
                ('Priority', models.TextField(choices=[('HIGH', 'HIGH'), ('LOW', 'LOW'), ('MEDIUM', 'MEDIUM')])),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.user')),
            ],
        ),
        migrations.CreateModel(
            name='Done',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_task_time', models.DateTimeField(auto_created=True)),
                ('assignee_name', models.TextField()),
                ('task_name', models.TextField()),
                ('description', models.TextField()),
                ('total_work_log', models.IntegerField()),
                ('updated_worklog', models.IntegerField()),
                ('created_task_time', models.DateTimeField(auto_now_add=True)),
                ('Priority', models.TextField(choices=[('HIGH', 'HIGH'), ('LOW', 'LOW'), ('MEDIUM', 'MEDIUM')])),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('task_id_done', models.ManyToManyField(to='ticket.Done')),
                ('task_id_inprogress', models.ManyToManyField(to='ticket.InProgress')),
                ('task_id_to_do', models.ManyToManyField(to='ticket.ToDo')),
            ],
        ),
    ]
